### ISSUE TITLE
tutorial miss evt_handler member in ble_cus_init_t struct

### ISSUE THREAD

**Issue by halecivo** [bjornspockeli/custom_ble_service_example#1]
ble_cus_evt_handler_t         evt_handler; is missing in STEP2

**Comment by halecivo** [comment]
this causes a compilation error in main.c services_init()
cus_init.evt_handler                = NULL;

**Comment by bjornspockeli** [comment]
Yes, I forgot to remove the 

`cus_init.evt_handler = NULL;`

statement in Step 3 where you initialize the service. THis has been fixed now.
