### ISSUE TITLE
sd_ble_gatts_hvx issue

### ISSUE THREAD

**Issue by foodloves** [bjornspockeli/custom_ble_service_example#4]
Hello,

I am using 14.1.0 SDK, I implemented the custom service and characteristic, but if adding CCCD(Client Characteristic Configuration Descriptor) with the custom value characteristic, the system will be reset after pushing cccd button in app, I can't know the reason,

when checking the issue point, the issue is happened with sd_ble_gatts_hvx function,

please help me the method to solve issue,
My email is gihyun.yun@ybrain.com 

thankful for your support and kindness in advance

Question : Should I change memory as to ram ?
currently start is 0x20002a68 and size is 0x2000ffff, how can I change it ? please..help me...

thanks

**Comment by foodloves** [comment]
please refer below for more information about issue,

https://devzone.nordicsemi.com/question/187570/the-cccd-of-custom-value-characteristic-with-nrf52832/

thanks.

**Comment by bjornspockeli** [comment]
Solved on the Nordic DevZone.
