### ISSUE TITLE
How to add more than 1 custom service?

### ISSUE THREAD

**Issue by LeonanFragaLeonardo** [bjornspockeli/custom_ble_service_example#7]
Hi, first of all, I would like to say that you have helped me a lot with your tutorial. Thank you for your excellent work.

But, how can I add more than one custom service?
I do these things:
 * Create a new Custom Service
 * Add new Characteristics
 * Add the new CUSTOM_SERV_UUID to advertising array in main.c
 * Set NRF_SDH_BLE_VS_UUID_COUNT to 2 inside the sdk_config.h
 * Initialize service. 

But when I try to run, my application stops to do advertising. 

I think I have two possible errors:
1 - I need to set the RAM_START and RAM_SIZE values.
2 - When I created my new service, I put this in an advertising package and this made it exceed the allowed 31-byte value of advertising.

Ps: My second custom service doesn't need to advertise. So, if I can remove from advertising and see those values when my peer is connected, I could do this, by I don't know how to do.

Could you help me to solve this issue?

**Comment by yoonlee95** [comment]
Just to piggyback on this question,
I there an equation for how much RAM memory we need for each service we add?
This is when we touch the MEMORY field in the ld file

**Comment by bjornspockeli** [comment]
Hi guys, I apologize for the slow response. There is no need for an equation as the SoftDevice will actually tell you if you have allocated to little RAM, i.e. it will return the application RAM start address. You can start a debug session with a breakpoint after the sd_ble_enable() call in nrf_sdh_ble_enable() in nrf_sdh_ble.c

If you have RTT logging enabled( should be enabled by default in the ble_app_template example) then the RTT output will be displayed in the Debug Terminal in Segger Embedded Studio, as shown in the screenshot below.

![cus_example_debug_log_output](https://user-images.githubusercontent.com/9253696/39585871-0f240598-4ef6-11e8-91b1-690e7ee6828e.png)


It is also possible to use the UART backend instead of the RTT backend by setting 
NRF_LOG_BACKEND_RTT_ENABLED to 0 and NRF_LOG_BACKEND_UART_ENABLED to 1 in sdk_config.h.
In both cases you'll see the following output in the Debug Terminal/Serial TErminal/RTT Viewer if you have allocated to little RAM for the SoftDevice.
```
<warning> nrf_sdh_ble: Insufficient RAM allocated for the SoftDevice.
<warning> nrf_sdh_ble: Change the RAM start location from 0x20002210 to 0x20002220.
<warning> nrf_sdh_ble: Maximum RAM size for application is 0xDDE0.
<error> nrf_sdh_ble: sd_ble_enable() returned NRF_ERROR_NO_MEM.
<error> app: ERROR 4 [NRF_ERROR_NO_MEM] at C:\Nordic_Semiconductor\SDK_Repository\nRF5_SDK\nRF5_SDK_15.0.0_a53641a\examples\ble_peripheral\custom_ble_service_example\main.c:663
PC at: 0x0002EF37
```

**Comment by bjornspockeli** [comment]
@yoonlee95  and @LeonanFragaLeonardo does this answer your question?

**Comment by LeonanFragaLeonardo** [comment]
Sorry for the delay. I solve my question.
I think my problem was three things.

1 - I was setting a UUID in advertising that was actually overloading the maximum size of 31 bytes, I removed the service from the advertising package. Staying like this:
 
  static ble_uuid_t m_adv_uuids [] = / ** <Universally unique service identifiers. * /
   {
       {BLE_UUID_WCS_SERVICE, BLE_UUID_TYPE_BLE}
   };

2 - My BASE UUIDs were different for services, I believe this could be causing the problem, but I do not have enough knowledge to confirm this.

3 - I did not have to change the values of RAM_SIZE and RAM_START_ADDRESS, since they were already correct.


Thank you for your reply.

**Comment by bjornspockeli** [comment]
@LeonanFragaLeonardo: Happy to hear that you solved the issue. 

1. If you need to advertise it in the future there is the option of putting the second VS UUID in a scan response packet. 

2. As long as you add the vendor specific UUID to the SD table using sd_ble_uuid_vs_add() prior to calling sd_ble_gatts_service_add() in the service initialization function and you have set NRF_SDH_BLE_VS_UUID_COUNT to 2 then you should be OK. 

3. Ok, I thought that you would have to increase them when adding another VS UUID, but apperently not.

**Comment by LeonanFragaLeonardo** [comment]
@bjornspockeli Thank you.
1 - I read this in your tutorial.  By the way, thank you very much for the excellent work.
2 - I didn't know about this. I'll read about this.
3 - This is a little bit strange for me, I thought that would be necessary.

Could this error be related to something else? Because when I did that, everything worked.

**Comment by bjornspockeli** [comment]
@LeonanFragaLeonardo Thank you, its nice to see that people find the tutorial useful!
Q2: Let me know if you have any further questions regarding this. 
Q3: I have not tested if adding another VS UUID requires you to allocate more RAM to the SoftDevice, but if you have done it and not changed the RAM settings, then it is evidently not needed. 

Generally, whenever you're seeing that the nRF device is not advertising after you flashed you should do the following:

1. Start a debug session
2. Set a breakpoint in app_error_handler_bare in app_error.c
3. Run the code and if you end up in the error handler, examine the call stack and identify the function that caused the error. 
4. Look up the error code in the SDK/SoftDevice API documentation on http://infocenter.nordicsemi.com/

**Comment by LeonanFragaLeonardo** [comment]
Hi @bjornspockeli.
Make sense. 😄 
I'll follow your tips. Thank you again.
