### ISSUE TITLE
custom_value_char_add is not defined in the header file.

### ISSUE THREAD

**Issue by isthatme** [bjornspockeli/custom_ble_service_example#8]
In the main README, in step 4 right at the beginning it says to declare custom_value_char_add in the header file. It won't compile (at least using GCC) if you follow this step, and this step is also not in the final ble_cus.h file.

**Comment by bjornspockeli** [comment]
@isthatme : Thanks for the report. You are correct, this should not be declared in the header as it is only used in ble_cus.c, i.e. a private function. This has been corrected in the README.md file in my latest commit.
